@baseUrl = http://localhost:3333

# @name create_account_is_admin
# @description Create a new account
# @method POST
# @path /accounts
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "isAdmin@mail.com",
  "password": "123456",
  "isAdmin": true
}

###

# @name create_account_is_not_admin
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Not John Doe",
  "email": "notAdmin@mail.com",
  "password": "654321",
  "isAdmin": false
}

###

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "isAdmin@mail.com",
  "password": "123456"
}
