@baseUrl = http://localhost:3333
@authToken = {{sessions.response.body.access_token}}


# @name create_account_is_admin
# @description Create a new account
# @method POST
# @path /accounts
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "isAdmin@mail.com",
  "password": "123456",
  "isAdmin": true
}

###

# @name create_account_is_not_admin
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Not John Doe",
  "email": "notAdmin@mail.com",
  "password": "654321",
  "isAdmin": false
}

###

# @name sessions
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "isAdmin@mail.com",
  "password": "123456"
}


###

# @name create_product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Cadeiras",
  "value": 5,
  "quantity": 1000
}


###

# @name create_client
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Chiaaa",
  "email": "chico2a@example.com",
  "phone": "(11) 12345-6799",
  "address": "Av. Paulista, 1000",
  "description": "Cliente preferencial"
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "clientId": "d618d92e-3f6b-4969-b86a-949189b67790",
  "products": [
    {
      "productId": "12619d21-769c-49ec-bd14-1cfecf1e7143",
      "quantity": 10
    },
    {
      "productId": "c90d9339-8577-4492-a286-76630975f6f9",
      "quantity": 5
    }
  ],
  "description": "aluguel do jogo",
  "discount": 10,
  "paymentMethod": "PIX"
}





